version: "2"
services:
  github-backup:
    image: mach4/python-gitlab-backup:latest
    container_name: "gitlab-backup"
    hostname: "gitlab-backup"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - HOST=${GITLAB_HOST}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - MAX_BACKUPS=10
      - TIME_ZONE=America/Montreal
    volumes:
      - ./data:/srv/var